### ISSUE TITLE
[typo] [ v2/en/components.md] Is is vividely recommended to use ...

### ISSUE THREAD

**Issue by susan51531** [openresty/openresty.org#103]
Is this a typo?
> Is is vividely recommended to use OpenResty's branch of LuaJIT (already bundled and enabled by default in OpenResty releases since 1.5.8.1).

Maybe change to this:
```diff
-Is is vividely recommended to use ...
+It is recommended to use ...
```

**Comment by agentzh** [comment]
@susan51531 Will you please create a pull request so that we can merge directly? Many thanks!

**Comment by thibaultcha** [comment]
@susan51531 Thanks for the patch!
