### ISSUE TITLE
Unzip the office source code with user Information.

### ISSUE THREAD

**Issue by ZhuoSiChen** [openresty/openresty.org#109]
When I unzip tar.gz which download from official site, The office  tar.gz package packs the user information into this tar.gz package.which useId was 1000 and usergroupId was 1003.
Vision number was openresty/1.15.8.1

**Comment by agentzh** [comment]
Yeah, it's better to use 0 user id and 0 user group to generate these tarballs. We'll do that for future releases. Existing ones won't get touched though.
