### ISSUE TITLE
rewrite_by_lua_no_postpone not working in server context

### ISSUE THREAD

**Issue by prkhr** [openresty/openresty.org#11]
Hi,
I am using **rewrite_by_lua** directive within server context followed by a nginx **rewrite** directive. I have **rewrite_by_lua_no_postpone on** in the http context.

Example conf:
```

server{
...
rewrite_by_lua_file lua/test.lua;
rewrite ^/test/(.*)$ /test1/$1 break;
...
}
```

However, in the server rewrite phase, nginx is evaluating the **rewrite** directive first and not the **rewrite_by_lua** directive which is unexpected as I have disabled lua rewrite postpone by setting **rewrite_by_lua_no_postpone** to on. 

In fact, to my surprise, the rewrite_by_lua directive gets evaluated after matching all the location handlers. The same configuration works fine in the **location** context.

How can I ensure that rewrite_by_lua gets evaluated before any **rewrite** and location handlers.

**Comment by agentzh** [comment]
@prkhr The `rewrite_by_lua` directive only runs in the "location rewrite" phase. It never runs in the "server rewrite" phase even when you put it in the server {} level (in this case, all the containing locations just inherit the same `rewrite_by_lua` setting).

**Comment by agentzh** [comment]
@prkhr BTW, your issue has nothing to do with the openresty.org repos which is just for the openresty.org site. A more suitable place for such things is the lua-nginx-module repos or the openresty-en mailing list.

**Comment by prkhr** [comment]
@agentzh Thanks for the clarification. I will use lua-nginx-module repo for any other issues.
