### ISSUE TITLE
官网好像挂了访问不了2020年8月16日18:35:42

### ISSUE THREAD

**Issue by kakaluote444** [openresty/openresty.org#124]
This repository is for the openresty.org web site, not for the OpenResty software.
So please do *not* report OpenResty issues in this repository.

Please, do not use Chinese here. This place is considered English only. If you
really want to use Chinese, please join and post to the openresty (Chinese)
mailing list instead. Please see https://openresty.org/en/community.html Thanks for
your cooperation.

**Comment by doujiang24** [comment]
Thanks for your report. yes, it's down for about 30-40 minutes and it's fixed now.
Please feel free to reopen this issue if you still have problem.

**Comment by kleisauke** [comment]
It seems it's still down, see for example: https://travis-ci.org/github/weserv/images/builds/718337135.
```
Could not connect to openresty.org:80 (54.215.206.164), connection timed out
```

Perhaps I should use a SSL connection here?:
https://github.com/weserv/images/blob/6e410e74240df52d61c73bb7e063023305e7ebfe/.travis.yml#L25
(fwiw, [the docs](https://openresty.org/en/linux-packages.html#ubuntu) mentions using an insecure connection when adding the APT repository)

**Comment by kleisauke** [comment]
I restarted the above mentioned Travis build and it seems to work now, thanks!
