### ISSUE TITLE
可以写一个kafka的插件，将数据直接存到kafka

### ISSUE THREAD

**Issue by NewsGitHub** [openresty/openresty.org#13]
可以写一个kafka的插件，将数据直接存到kafka，这个用途估计很广泛

**Comment by agentzh** [comment]
@NewsGitHub Please, no Chinese here. This place is considered English only. If you really
want to use Chinese, please join the openresty (Chinese) mailing list instead.
Please see https://openresty.org/#Community Thanks for your cooperation.

Regarding your question, yes, you're encouraged to contribute a lua-resty-kafka library. I don't have the time to do it myself in the foreseeable future.
