### ISSUE TITLE
Please do not block User-Agent: Python-urllib

### ISSUE THREAD

**Issue by quodt** [openresty/openresty.org#14]
i'm getting 403 with python urllib and urllib2:

```
   >>> urllib2.urlopen('https://openresty.org/download/ngx_openresty-1.9.3.1.tar.gz').code
   Traceback (most recent call last):
   ...
   urllib2.HTTPError: HTTP Error 403: Forbidden
```

if i pass no User-Agent or a custom User-Agent everything is fine:

```
   >>> opener = urllib2.build_opener()
   >>> opener.addheaders = [('User-agent', 'Mozilla/5.0')]
   >>> opener.open('https://openresty.org/download/ngx_openresty-1.9.3.1.tar.gz').code
   200

   >>> opener = urllib2.build_opener()
   >>> opener.addheaders = []
   >>> opener.open('https://openresty.org/download/ngx_openresty-1.9.3.1.tar.gz').code
   200
```

Using "Python-urllib" as User-Agent results in 403, independently of any following python version ("Python-urllib", "Python-urllib/2.7", "Python-urllib/3.4"). I've also seen that some potential bots are blocked as well. For example "EmailSiphon" and "autoemailspider". So i assume "Python-urllib" is on that list as well.

Could you please remove Python-urllib from that list? Otherwise good-natured python clients like zc.buildout are not able to download openresty.

**Comment by agentzh** [comment]
@quodt Hmm, strange. I fail to reproduce it on my side with simple curl and that User-Agent string. Anyway, I've disabled the user-agent checks altogether on the server. Please try it again after a few minutes.

Please let me know if it works for you.

Thanks for the report!

**Comment by quodt** [comment]
@agentzh i am still getting 403

```
curl -I -H "User-Agent: Python-urllib/2.7" https://openresty.org
HTTP/1.1 403 Forbidden
```

**Comment by agentzh** [comment]
@quodt Ah, thanks for the test command. I've adjusted the settings and it works for me now:

```
$ curl -I -H "User-Agent: Python-urllib/2.7" https://openresty.org
HTTP/1.1 200 OK
...
```

Thanks for your time!

**Comment by quodt** [comment]
@agentzh confirm. Now it is working for me as well

```
curl -I -H "User-Agent: Python-urllib/2.7" https://openresty.org
HTTP/1.1 200 OK
...
```

closing.
