### ISSUE TITLE
nginx proxy_cache_methods doesn't work

### ISSUE THREAD

**Issue by nguyennhatkhang92** [openresty/openresty.org#15]
Hi, 
I'm try use nginx proxy_cache for caching large file. The following is my idea:
         
     Browser --> Nginx --> Storage
- Nginx is a function of caching and proxy server.
- Storage is contain files server.
- I'm have used ngx.var.upstream_cache_status to determine the status of the HIT file caching but it does'n work, nil value. Then I found this: https://github.com/openresty/lua-nginx-module/issues/125 . I would caching file with only GET method and use HEAD method is checked file caching done(HIT)  but proxy_cache_methods doesn't work, proxy_method also. I'm try request from Browser with HEAD, GET method then nginx proxy pass to Storage server with GET methods, I do not understand what the reason.

**Comment by agentzh** [comment]
@nguyennhatkhang92 Please, do not cross-post. It's annoying. Also, this ticket has nothing to do with the openresty.org site itself. I'm closing this.
