### ISSUE TITLE
https://qa.openresty.org - Cloudflare HTTPS error

### ISSUE THREAD

**Issue by rugk** [openresty/openresty.org#16]
![tlserrcloudflare](https://cloud.githubusercontent.com/assets/11966684/10567324/1e174cac-7601-11e5-81ee-64a27d3d5351.png)

Important part:
> The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. [Additional troubleshooting information here](https://support.cloudflare.com/hc/en-us/articles/200721975).

**Comment by agentzh** [comment]
@rugk This is a known issue. qa.openresty.org does not really support https since my SSL certificate for openresty.org does not include that (to save money). Thank you for the report anyway.

**Comment by J0WI** [comment]
No need to waste money, you can get a free certificate from StartCom or from Let's Encrypt (soon).

**Comment by agentzh** [comment]
@J0WI Actually I'm already using a free cert from StartCom for openresty.org but it only supports two (sub)domains and I've already been using it for openresty.org and www.openresty.org. That's why qa.openresty.org is excluded.

**Comment by rugk** [comment]
You can get another free cert from StartSSL with another subdomain (e.g. openresty.org and qa.openresty.org) or you can use another CA - like Let's Encrypt [which is now trusted](https://letsencrypt.org/2015/10/19/lets-encrypt-is-trusted.html). If you want to use Let's Encrypt you can sign up for the beta or wait until November for general availability.

**Comment by agentzh** [comment]
@rugk The first approach sounds feasible to me. I'll give it a shot when I have a chance. Thank you.

**Comment by rugk** [comment]
And what progress did you make?

**Comment by agentzh** [comment]
@rugk Sorry, no progress yet. Too busy with other things.

**Comment by J0WI** [comment]
letsencrypt is now in public beta

**Comment by agentzh** [comment]
@J0WI Thanks for the pointer. Let's Encrypt looks interesting though it currently has problems on Windows XP it seems:

https://github.com/letsencrypt/letsencrypt/issues/1660

Hopefully it will get fixed soon :)

**Comment by rugk** [comment]
Possibly [this](https://github.com/letsencrypt/letsencrypt/issues/1660#issuecomment-162084902) helps? In case you use Apache - otherwise you may have to rewrite it.
*Disclaimer:* Did not tested the linked solution. I have no idea whether/how and (if so) why it works.

**Comment by agentzh** [comment]
@rugk No, it's not enough. That hack just avoids rewriting http:// requests to https ones for XP clients.

**Comment by agentzh** [comment]
Okay, I've just fixed this by using a different SSL certificate. Please verify on your side. Thanks!

**Comment by rugk** [comment]
Works. :smile:
