### ISSUE TITLE
Is Redis Connection too Frequent ？

### ISSUE THREAD

**Issue by gaoguoxin** [openresty/openresty.org#17]
In the nginx config file  I have the following code, for the location where the $request_uri matched,I connect the redis and query the value of the key.The code bellow can work correct,But I think  the code has some shortcomings：every time I must reconnect the redis server,I think the redis server will bear great pressure.Is there other good solution for that?
```lua
  location ~* /(\w+\/\w+) {
    set $qstring $1;
    access_by_lua '
      local redis = require "resty.redis"
      local red = redis:new()
      red:connect("127.0.0.1", 6379)
      red:set_timeout(1000)
      ok, err = red:hget("repo:" .. ngx.var.qstring .. ".git", "m")
      if ok and ok ~= ngx.null then
        return ngx.redirect("http://" .. ok .. ngx.var.request_uri)
      end
    ';
    try_files $request_uri $uri @project_name;
  }
```

**Comment by doujiang24** [comment]
Hello,

you can use set_keepalive

https://github.com/openresty/lua-resty-redis#set_keepalive


2015-11-19 16:38 GMT+08:00 gaoguoxin <notifications@github.com>:
