### ISSUE TITLE
failed to load external Lua file 

### ISSUE THREAD

**Issue by xu4wang** [openresty/openresty.org#18]
I am using mac os, with openresty 1.9.3.2

The issue I met is similar to:
http://stackoverflow.com/questions/28087228/openresty-content-by-lua-file

The server cannot load external Lua script:
2015/11/30 21:03:06 [error] 61190#0: *1 failed to load external Lua file "/Users/wangxu/Documents/work/tms/dev/tms/lua/req.lua": cannot open /Users/wangxu/Documents/work/tms/dev/tms/lua/req.lua: Permission denied, client: 127.0.0.1, server: , request: "GET /v1/p HTTP/1.1", host: "127.0.0.1"

However If I copy the lua file into /tmp and use 
content_by_lua_file "/tmp/req.lua";

Everything is OK.

I checked the path, the permissions.. they are all correct.

**Comment by agentzh** [comment]
@xu4wang This is really about basic *NIX permissions, not OpenResty. To solve a path (by the OS), all the directories on the path should be executable by the current system account, not just the file being readable. This is why putting the file under /tmp works for you since the /tmp directory itself is very permissive.

**Comment by xu4wang** [comment]
Thanks for the quick response...  Problem solved.
I realized the worker process is running under nobody instead of root, even I run nginx with sudo..

**Comment by crockpotveggies** [comment]
Visitor from the future with a permissions-based problem. Ran into a similar issue where the process is running as `nobody`. Does anyone know how to run it as root? Not concerned about security, this isn't a public service.

**Comment by crockpotveggies** [comment]
Nevermind, solved this rather quickly. It can be done with the nginx config:
```
user root root;
```

**Comment by agentzh** [comment]
@crockpotveggies It's a bad idea to run the nginx workers as `root` in production though since it exposes higher security risk (once the hacker gets his way into the nginx worker, he becomes root).

**Comment by crockpotveggies** [comment]
It's a private network not exposed to the outside Internet. Nuff said 😉

**Comment by transtone** [comment]
In my Gentoo, to avoid 404, It must set these two steps:
1. file use a `absolute` path.
2. add charset like: `charset utf-8;  `

**Comment by duan1998** [comment]
![image](https://user-images.githubusercontent.com/35530193/151709693-c43774cb-1a30-44c1-8fe9-7fad542ccb30.png)
after modifing this text from "user : nobody" to "user : my user name",everything is ok
