### ISSUE TITLE
The survey page

### ISSUE THREAD

**Issue by warmchang** [openresty/openresty.org#22]
Dear agentzh,

Pls tell me where can I find the "surevey" page (https://openresty.org/survey/). The code hasn't been commited in this repository?

Thx!

**Comment by agentzh** [comment]
@warmchang It has its own repos, namely `openresty-survey`. It's currently still a private repos but will eventually go opensourced. I'll give you access.

**Comment by warmchang** [comment]
@agentzh , I got it, thank you! :-)
