### ISSUE TITLE
incorrect yum repo directory name

### ISSUE THREAD

**Issue by kev111** [openresty/openresty.org#38]
On the website (http://openresty.org/en/linux-packages.html) the baseurl is the following line: baseurl=https://copr-be.cloud.fedoraproject.org/results/openresty/openresty/epel-$releasever-$basearch/

On RHEL Server, the $releasever variable expands to 7Server or 7Client (if using version 7).  However, the actual yum repo at that url is only epel-7-x86_64/ and not epel-7Server-x86_64/.  This means that the yum repo does not actually work when specifying $releasever in the baseurl.

FIX: please make links named "epel-<version><OS type>-<basearch>" to the epel-<version>-<basearch> directory on the yum repo.  For example, create a link named "epel-7Server-x86_64" to "epel-7-x86_64" on the yum repo.  Thanks.

**Comment by agentzh** [comment]
@kev111 Thanks for the report! Because I have no control over that yum repos run by Fedora COPR, I'll just make another dedicated document paragraph for RHEL.

**Comment by agentzh** [comment]
@kev111 Fixed the docs: http://openresty.org/en/linux-packages.html#rhel
