### ISSUE TITLE
Broken link in chinese site.

### ISSUE THREAD

**Issue by warmchang** [openresty/openresty.org#46]
Hi, @agentzh 

All the link of "openresty.html" are broken in cn site, maybe should add the redirection plicy to "/" for this.

Accesee "https://openresty.org/cn/openresty.html", got the "Gateway Timeout".

![image](https://cloud.githubusercontent.com/assets/13084624/18026833/28bd6990-6c85-11e6-8396-b20a98b879ea.png)

**Comment by agentzh** [comment]
@warmchang What server IP addresses are you hitting? Will you provide that? The link works on my side (San Francisco) and on an Aliyun box (at Hongzhou) though. Also, it would be helpful if you can provide your own public IP address too when the problem occurs. Thanks!

**Comment by agentzh** [comment]
@warmchang And providing the raw HTTP response header could be helpful as well. Many thanks!

**Comment by warmchang** [comment]
@agentzh I try again, and it look like ok now. Maybe there are some problem about the internet provider.

But the 301 redirect take so long time (10 s):

![image](https://cloud.githubusercontent.com/assets/13084624/18132175/517d841e-6fc8-11e6-99fb-73c25a7176a2.png)


The http header and public ip are followed:

`my public ip: 112.64.61.189 Chinese Unicom`

```
Request URL:https://openresty.org/cn/openresty.html
Request Method:GET
Status Code:301 Moved Permanently
Remote Address:60.217.32.117:443
```

```
Accept-Ranges:bytes
Connection:keep-alive
Content-Length:178
Content-Type:text/html
Date:Wed, 31 Aug 2016 14:10:57 GMT
Location:/cn/
Oct-Response-Info:0000050000500005077540775400001
Oct-Upstream:52.76.49.101,115.238.245.220,123.157.129.151
Server:YunFanCDN
X-CDN-ReqID:BkNeAC9VV8blaYAAC
YF-ID:bzjsx1s009132p
YF-ID:bsdly1a002117p
YF-ID:czjhz1s005208p
```

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Cookie:__utmt=1; __utma=37978621.824986353.1472652342.1472652342.1472652342.1; __utmb=37978621.3.10.1472652342; __utmc=37978621; __utmz=37978621.1472652342.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
Host:openresty.org
Pragma:no-cache
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
```

**Comment by agentzh** [comment]
@warmchang Thanks for the info! We're working on a fix for the 301 slowness thing.

**Comment by warmchang** [comment]
@agentzh Welcome!
