### ISSUE TITLE
OpenResty China 2016 Conference: Call for Conference Proposals

### ISSUE THREAD

**Issue by moonbingbing** [openresty/openresty.org#49]
The OpenResty China 2016 Conference will be held on Dec. 10 in Shenzhen, China.

The Conference Organizing Committee is currently accepting proposals for the OpenResty China 2016 conference. If you want to submit a proposal ,please send an email  to talk@openresty.org  with your proposal's detail.  

Before submitting a proposal, please review the submission and speaker requirements below.

Presentation Criteria:
- Should be 40 minutes in length and limited to one speaker
- Can be in either English or Mandarin
- Must be associated with the OpenResty technology stack
- Not accept any form of ad content

Welcome to the OpenResty party!

**Comment by thibaultcha** [comment]
Closing this since it seems a bit outdated nowadays :)
