### ISSUE TITLE
openresty.org apex CNAME?

### ISSUE THREAD

**Issue by geraldcombs** [openresty/openresty.org#61]
I'm unable to browse to openresty.org due to a DNS failure. It looks like openresty.org has a top-level CNAME defined:

openresty.org.		3600	IN	CNAME	openresty-org-635249771.ap-southeast-1.elb.amazonaws.com.

See http://serverfault.com/a/613830/9470 for details on why this is prohibited.

**Comment by agentzh** [comment]
@geraldcombs I was well aware of this issue. The reason behind it is that our CDN provider in mainland China requires a CNAME to function properly. We'll probably migrate to the `www.` subdomain for everything soon.

**Comment by agentzh** [comment]
Already fixed now.
