### ISSUE TITLE
你好,我在安装openresty后使用redis

### ISSUE THREAD

**Issue by yangyaoweng** [openresty/openresty.org#9]
My system is  ubuntu14.04
apt-get install libreadline-dev libpcre3-dev libssl-dev perl build-essential
I installed these options
./configure --prefix=/opt/openresty
--without-http_redis2_module
--without-http_redis_module
--without-lua_resty_redis
--without-lua_cjson
--with-http_iconv_module
--without-http_set_misc_module
The installation process without any problems，Nginx is running normally，Can parse lua
But can't identify redis2
unknown directive "redis2_query" 
On the Internet looking for a long time didn't find the solution，Redis can run normally
I install ngx_openresty-1.7.4.1

**Comment by agentzh** [comment]
@yangyaoweng Seems like you are using the wrong nginx. OpenResty's nginx is located at `/opt/openresty/nginx/sbin/nginx` according to your `./configure` line.

**Comment by agentzh** [comment]
Consider it resolved.
